[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dunno"
version = "0.0.0"
description = "Dunno local development package"
authors = [ { name = "AIT200-org" } ]
readme = "README"
